### ISSUE TITLE
Google translate JSON error

### ISSUE THREAD

**Issue by Frigyes06** [mxrch/darkshot#12]
```Translation of keywords...
Traceback (most recent call last):
  File "run.py", line 55, in <module>
    start()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 52, in start
    main(threads, mode, algo, debug, clean, resume_ro)
  File "/home/frigyes/Desktop/darkshot/main.py", line 44, in main
    words = translate_keywords(cfg["keywords_langs"], cfg["words_to_translate"])
  File "/home/frigyes/Desktop/darkshot/lib/translate.py", line 9, in translate_keywords
    translation = translator.translate(word, lang_tgt=code)
  File "/home/frigyes/.local/lib/python3.8/site-packages/google_trans_new/google_trans_new.py", line 188, in translate
    raise e
  File "/home/frigyes/.local/lib/python3.8/site-packages/google_trans_new/google_trans_new.py", line 152, in translate
    response = json.loads(response)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1031 (char 1030)
```

**Comment by ToasterPool** [comment]
I have the same issue

Traceback (most recent call last):
  File "C:\darkshot\run.py", line 55, in <module>
    start()
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\darkshot\run.py", line 52, in start
    main(threads, mode, algo, debug, clean, resume_ro)
  File "C:\darkshot\main.py", line 27, in main
    log(f"Debug mode : {'ACTIVATED' if debug else 'DEACTIVATED'}", timecode=dirname, cfg=cfg, level="VALUABLE", hidden=False, debug=debug)
  File "C:\darkshot\lib\log.py", line 28, in log
    with open(path, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\2021-09-08_214257.txt'

C:\darkshot>python run.py

Traceback (most recent call last):
  File "C:\darkshot\run.py", line 55, in <module>
    start()
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\darkshot\run.py", line 52, in start
    main(threads, mode, algo, debug, clean, resume_ro)
  File "C:\darkshot\main.py", line 27, in main
    log(f"Debug mode : {'ACTIVATED' if debug else 'DEACTIVATED'}", timecode=dirname, cfg=cfg, level="VALUABLE", hidden=False, debug=debug)
  File "C:\darkshot\lib\log.py", line 28, in log
    with open(path, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\2021-09-08_214302.txt'

C:\darkshot>cd /

C:\>cd darkshot-master

C:\darkshot-master>python -m pip install -r requirements.txt
Requirement already satisfied: httpx in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (0.19.0)
Requirement already satisfied: google_trans_new in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (1.1.9)
Requirement already satisfied: pytesseract in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (0.3.8)
Requirement already satisfied: opencv-python in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 4)) (4.5.3.56)
Requirement already satisfied: pillow in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 5)) (8.3.2)
Requirement already satisfied: scrapy in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 6)) (2.5.0)
Requirement already satisfied: termcolor in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 7)) (1.1.0)
Requirement already satisfied: beautifultable in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: reprint in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 9)) (0.6.0)
Requirement already satisfied: click in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 10)) (8.0.1)
Requirement already satisfied: luhn in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 11)) (0.2.0)
Requirement already satisfied: imagehash in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 12)) (4.2.1)
Requirement already satisfied: certifi in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from httpx->-r requirements.txt (line 1)) (2021.5.30)
Requirement already satisfied: httpcore<0.14.0,>=0.13.3 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from httpx->-r requirements.txt (line 1)) (0.13.6)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from httpx->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: sniffio in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from httpx->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: charset-normalizer in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from httpx->-r requirements.txt (line 1)) (2.0.4)
Requirement already satisfied: numpy>=1.19.3 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from opencv-python->-r requirements.txt (line 4)) (1.21.2)
Requirement already satisfied: h2<4.0,>=3.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (3.2.0)
Requirement already satisfied: parsel>=1.5.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (1.6.0)
Requirement already satisfied: cryptography>=2.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (3.4.8)
Requirement already satisfied: protego>=0.1.15 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (0.1.16)
Requirement already satisfied: itemadapter>=0.1.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (0.4.0)
Requirement already satisfied: lxml>=3.5.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (4.6.3)
Requirement already satisfied: zope.interface>=4.1.3 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (5.4.0)
Requirement already satisfied: itemloaders>=1.0.1 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (1.0.4)
Requirement already satisfied: cssselect>=0.9.1 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: pyOpenSSL>=16.2.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (20.0.1)
Requirement already satisfied: service-identity>=16.0.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (21.1.0)
Requirement already satisfied: Twisted[http2]>=17.9.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (21.7.0)
Requirement already satisfied: PyDispatcher>=2.0.5 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (2.0.5)
Requirement already satisfied: queuelib>=1.4.2 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (1.6.2)
Requirement already satisfied: w3lib>=1.17.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from scrapy->-r requirements.txt (line 6)) (1.22.0)
Requirement already satisfied: wcwidth in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from beautifultable->-r requirements.txt (line 8)) (0.2.5)
Requirement already satisfied: colorama in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from reprint->-r requirements.txt (line 9)) (0.4.4)
Requirement already satisfied: backports.shutil-get-terminal-size in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from reprint->-r requirements.txt (line 9)) (1.0.0)
Requirement already satisfied: six in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from reprint->-r requirements.txt (line 9)) (1.16.0)
Requirement already satisfied: scipy in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from imagehash->-r requirements.txt (line 12)) (1.7.1)
Requirement already satisfied: PyWavelets in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from imagehash->-r requirements.txt (line 12)) (1.1.1)
Requirement already satisfied: cffi>=1.12 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from cryptography>=2.0->scrapy->-r requirements.txt (line 6)) (1.14.6)
Requirement already satisfied: pycparser in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from cffi>=1.12->cryptography>=2.0->scrapy->-r requirements.txt (line 6)) (2.20)
Requirement already satisfied: hyperframe<6,>=5.2.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from h2<4.0,>=3.0->scrapy->-r requirements.txt (line 6)) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from h2<4.0,>=3.0->scrapy->-r requirements.txt (line 6)) (3.0.0)
Requirement already satisfied: anyio==3.* in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from httpcore<0.14.0,>=0.13.3->httpx->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: h11<0.13,>=0.11 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from httpcore<0.14.0,>=0.13.3->httpx->-r requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: idna>=2.8 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from anyio==3.*->httpcore<0.14.0,>=0.13.3->httpx->-r requirements.txt (line 1)) (3.2)
Requirement already satisfied: jmespath>=0.9.5 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from itemloaders>=1.0.1->scrapy->-r requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: pyasn1 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from service-identity>=16.0.0->scrapy->-r requirements.txt (line 6)) (0.4.8)
Requirement already satisfied: pyasn1-modules in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from service-identity>=16.0.0->scrapy->-r requirements.txt (line 6)) (0.2.8)
Requirement already satisfied: attrs>=19.1.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from service-identity>=16.0.0->scrapy->-r requirements.txt (line 6)) (21.2.0)
Requirement already satisfied: twisted-iocpsupport~=1.0.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from Twisted[http2]>=17.9.0->scrapy->-r requirements.txt (line 6)) (1.0.2)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from Twisted[http2]>=17.9.0->scrapy->-r requirements.txt (line 6)) (3.10.0.2)
Requirement already satisfied: Automat>=0.8.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from Twisted[http2]>=17.9.0->scrapy->-r requirements.txt (line 6)) (20.2.0)
Requirement already satisfied: incremental>=21.3.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from Twisted[http2]>=17.9.0->scrapy->-r requirements.txt (line 6)) (21.3.0)
Requirement already satisfied: constantly>=15.1 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from Twisted[http2]>=17.9.0->scrapy->-r requirements.txt (line 6)) (15.1.0)
Requirement already satisfied: hyperlink>=17.1.1 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from Twisted[http2]>=17.9.0->scrapy->-r requirements.txt (line 6)) (21.0.0)
Requirement already satisfied: priority<2.0,>=1.1.0 in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from Twisted[http2]>=17.9.0->scrapy->-r requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: setuptools in c:\users\daniel ridgway\appdata\local\programs\python\python39\lib\site-packages (from zope.interface>=4.1.3->scrapy->-r requirements.txt (line 6)) (49.2.1)

C:\darkshot-master>python check_ocr_langs.py
All OCR langs are installed correctly.

C:\darkshot-master>cd /

C:\>python run.py
python: can't open file 'C:\run.py': [Errno 2] No such file or directory

C:\>cd darkshot-master

C:\darkshot-master>python run.py

Translation of keywords...
Traceback (most recent call last):
  File "C:\darkshot-master\run.py", line 55, in <module>
    start()
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\darkshot-master\run.py", line 52, in start
    main(threads, mode, algo, debug, clean, resume_ro)
  File "C:\darkshot-master\main.py", line 44, in main
    words = translate_keywords(cfg["keywords_langs"], cfg["words_to_translate"])
  File "C:\darkshot-master\lib\translate.py", line 9, in translate_keywords
    translation = translator.translate(word, lang_tgt=code)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\google_trans_new\google_trans_new.py", line 188, in translate
    raise e
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\site-packages\google_trans_new\google_trans_new.py", line 152, in translate
    response = json.loads(response)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Daniel Ridgway\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1031 (char 1030)

**Comment by ToasterPool** [comment]
+1 I have the same issue

**Comment by Andrei1744** [comment]
+1 same issue

**Comment by s0r3-glitch** [comment]
+1 same issue

**Comment by Warrior-spec** [comment]
well i am having same problem any solution found

**Comment by s0r3-glitch** [comment]
> 
> 
> well i am having same problem any solution found

If you run darkshot from [this fork](https://github.com/meoww/darkshot) it should fix the problem. I have had an issue where I get a keyerror during runtime but I have no idea whats causing it
